spring:
  datasource:
    driver-class-name: org.h2.Driver

  application:
    name: scg-sample

  h2:
    console:
      enabled: true

  r2dbc:
    url: r2dbc:h2:mem:///test
    username: sa

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true