spring:

  application:
    name: scg-sample

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      redis-route-definition-repository:
        enabled: true

logging:
  level:
    root: debug